feat: migrate JWT auth class to jsforce
jsforce/jsforce pull request #1249
Opened 2022-06-30 16:15 UTC by WillieRuemmele

Migrate the `JwtOAuth2` class from `sfdx-core` to `jsforce` so that other `jsforce` consumers can use that too

2022-07-01 22:15 UTC, paustint requested changes

2022-07-01 22:15 UTC, paustint commented on src/jwtOAuth2.ts
> +};//here
Is this `//here` comment supposed to be included?

2022-07-06 15:34 UTC, WillieRuemmele commented
https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/client/metadataApiDeploy.ts#L317
https://github.com/salesforcecli/plugin-source/blob/main/src/deployCommand.ts#L181

can be simplified once this is merged

2022-07-08 17:24 UTC, shetzel approved these changes
Just some nits (and the package-lock.json changes)

2022-07-08 17:24 UTC, shetzel commented on src/api/metadata.ts
> +    delete options.rest;
Doesn't look like you need to delete `options.rest`.  You can probably just do:
`const { id, rest } = options;`
and use them below.

2022-07-08 17:24 UTC, shetzel commented on src/jwtOAuth2.ts
> +export default JwtOAuth2;
nit: you can move this to the class definition to avoid this line.  I.e., line 12 above becomes:
`export default class JwtOAuth2 extends OAuth2 {`

2022-07-11 15:31 UTC, merged