Set correct entrypoint to module in package.json
jsforce/jsforce pull request #1574
Opened 2024-09-06 17:17 UTC by schwarmco

Fixes #1560
Fixes #1553

2024-09-24 15:51 UTC, cristiand391 commented on package.json
> +  "module": "./index",
we don't ship an ESM build yet so it's better to just remove this field (`module` in pjson make tools think this is the ESM entrypoint, we don't want CJS be treated as ESM).

2024-09-24 15:52 UTC, cristiand391 requested changes
hey @schwarmco, sorry for the late reply.

jsforce v3 doesn't ship an ESM build yet so it will be better to just remove the `module` field for now.

2024-10-08 10:28 UTC, schwarmco commented
> jsforce v3 doesn't ship an ESM build yet so it will be better to just remove the `module` field for now.

that makes perfect sense. can confirm it still works with the import-syntax.
i've rebased and removed the line from package.json

2024-10-08 12:12 UTC, cristiand391 approved these changes

2024-10-08 14:00 UTC, cristiand391 commented
we got 1 external NUT failure but it's unrelated to this change, merging this...

thanks for the PR @schwarmco :)

2024-10-08 14:00 UTC, merged